#!/usr/local/bin/php
<?php

textmark('Test a todo with an output', function () {
  return('x > This is a simple output ' . date('r'));
});

textmark('Test Second Level Todo', function() {
  textmark('Test Third Level Todo 1');
  textmark('Test Third Level Todo 2');
  textmark('Test Third Level Todo 3', fn() => "x > Hola!\n\n> ¿Como Estas?");
  textmark('Test Third Level Todo 4');
  return('~');
});

textmark('Test Another Second Level Todo', function() {
  return('x > Hello, World ' . date('r'));
});